 server:
   port: 8090

 spring:
   datasource:
     url: jdbc:mysql://localhost:3306/team?user=root&password=root
     driver-class-name: com.mysql.cj.jdbc.Driver
   application:
     name : Team-Service
   jpa:
     show-sql: true
     hibernate:
       ddl-auto: update
#     properties:
#       hibernate:
#         dialect: org.hibernate.dialect.MySQLDialect
   config:
     import: configserver:http://localhost:8093



 management:
   endpoints:
     web:
       exposure:
         include:
           - beans
           - info
           - health

   health:
     circuitbreakers:
       enable: true








