name: Example workflow for Maven using Snyk
on:
  workflow_dispatch
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: list dir contents
        run: ls
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Give Permission
        run: chmod +x ./mvnw

