name: Example workflow for Maven using Snyk
on:
  workflow_dispatch

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install and run Snyk
        run: |
          curl -LO https://static.snyk.io/cli/latest/snyk-linux
          chmod +x ./snyk-linux
          sudo mv ./snyk-linux /usr/local/bin/snyk
          npx snyk auth ${{ secrets.SNYK_TOKEN }}
          npx snyk test --org=yuvrajarora070
