name: Example workflow for Maven using Snyk

on:
  workflow_dispatch

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Give Permission to Maven Wrapper
        run: chmod 777 ./mvnw

      - name: Install the Snyk CLI
        run: |
          curl -LJO https://github.com/snyk/snyk/releases/latest/download/snyk-linux
          chmod +x ./snyk-linux
          sudo mv ./snyk-linux /usr/local/bin/snyk

      - name: Authenticate Snyk CLI
        run: |
          echo "Snyk Token: $SNYK_TOKEN"
          snyk auth --api-token=${{ secrets.SNYK_TOKEN }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk to check for vulnerabilities
        run: snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Upload results to Snyk
        run: snyk monitor
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
