name: Example workflow for Maven using Snyk
on:
  workflow_dispatch
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: list dir contents
        run: ls
      - name: Give Permission
        run: chmod 777 ./mvnw
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Install Snyk CLI
        run: |
          curl https://static.snyk.io/cli/latest/snyk-linux -o snyk
          chmod +x ./snyk
          mv ./snyk /usr/local/bin/
      - name: Authenticate Snyk CLI
        run: snyk auth
      - name: Upload results to Snyk
        run: snyk test --json | snyk monitor
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
