name: Example workflow for Maven using Snyk
on:
  workflow_dispatch

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Give Permission to Maven Wrapper
        run: chmod 777 ./mvnw

      - name: Install the Snyk CLI
        run: |
          curl https://static.snyk.io/cli/latest/snyk-linux -o snyk
          chmod +x ./snyk-linux
          sudo mv ./snyk-linux /usr/local/bin/snyk

      - name: Run Snyk to check for vulnerabilities
        run: |
          npx snyk auth ${{ secrets.SNYK_TOKEN }}
          npx snyk test ${{ secrets.SNYK_ORG }}

      - name: Upload results to Snyk
        run: snyk monitor
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
