name: Example workflow for Maven using Snyk
on: 
  workflow_dispatch
jobs:
  security:
    runs-on: linux-latest
    steps:
      - uses: actions/checkout@master
      - name: Give Permission
        run: chmod 777 ./mvnw
      - name: install snyk cli
        run: |
          curl https://static.snyk.io/cli/latest/snyk-linux -o snyk
          chmod +x ./snyk
          mv ./snyk /usr/local/bin/ 
      - name: Authnticate the Snyk
        run: snyk auth
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven-3-jdk-17@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
